### ISSUE TITLE
Doesn't Launchwith Logitech G920 on Arch Linux

### ISSUE THREAD

**Issue by xpander69** [berarma/oversteer#1]
```
xpander@arch ~ $ lsusb
Bus 001 Device 005: ID 046d:c262 Logitech, Inc. 
```
Launching without root access gives me:
```
Traceback (most recent call last):
  File "./oversteer.py", line 10, in <module>
    from wheels import Wheels
  File "/home/xpander/Build_Projects/oversteer-master/wheels.py", line 4, in <module>
    import pyudev
ModuleNotFoundError: No module named 'pyudev'
```

Launching with _gksudo_ draws a small window for a less than second and then quits, without any errors shown in the terminal.

**Comment by xpander69** [comment]
ok i didnt have python-udev package installed. works now! i Will close it :)

would be nice to have the README updated with the needed package list

**Comment by berarma** [comment]
Thanks for the report.

You are missing some required packages. In case you are using some Debian derivative you can install the dependencies with the following command:
```apt install python3-gi python3-pyudev python3-xdg```

I'm very sorry because this should be solved using an installer or some packaging but this is my first Python program and I'm figuring out what's the best method to do it.

**Comment by xpander69** [comment]
we posted at the same time :) yeah i figured out.. on arch the missing packge was python-udev
its all fine. Love the GUI, very nice work!

**Comment by berarma** [comment]
> ok i didnt have python-udev package installed. works now! i Will close it :)
> would be nice to have the README updated with the needed package list

Yes, yes, I'm going to do it now. Sorry for the inconvenience. Glad it's working now. :)
