### ISSUE TITLE
G923 support

### ISSUE THREAD

**Issue by kdw2060** [berarma/oversteer#36]
Hi,

I was wondering if the new Logitech G923 wheel could also be supported or if you know if Linux kernel drivers for this wheel are planned? I know this isn't really a question about Oversteer, but couldn't find any info on driver development and you probably do know where to find this information (i'm on a debian-based distro).

I thought it would be supported out of the box, but alas it seems like it´s too different from the G92/920.

Thank you for any info you might have.

**Comment by berarma** [comment]
Hi,

I know nothing. I'd look into new kernel changelogs, although some new driver might emerge from somewhere else. it might take a considerable time to get it properly supported since it isn't a very appealing upgrade and there's an extra feature to support which is undocumented as of yet. But this is an oppinion, I don't really know what will happen.

**Comment by ZRtmWrJqXcjbqBLIMBYMCeUw** [comment]
Hello @berarma,

I would like this issue reopened as I have found some changes that can be made to the Oversteer software that will allow it to work correctly with the G923 wheel.

I have looked at some kernel mailing lists (e.g. [here](https://patchwork.kernel.org/patch/7114611/) and [here](https://patchwork.kernel.org/patch/11184749/)) and through the kernel source code (e.g. drivers/hid-logitech-hidpp.c) and found defintions for other steering wheels such as the G29 and G920.

Overall, I have learned from this that recent Logitech steering wheels use the HID++ protocol and that some minor kernel driver tweaks will likely need to be made to get the G923 to work as well. I will gladly move all of this somewhere else as I do realized modifying the kernel is far beyond the scope of this project, I just think it would be a good idea to have this somewhere easily accessible, such as this project, for anyone that might be in the same situation as me and @kdw2060.

Thanks @berarma for all your work on this project.

**Comment by berarma** [comment]
Hi @ZRtmWrJqXcjbqBLIMBYMCeUw,

> Overall, I have learned from this that recent Logitech steering wheels use the HID++ protocol and that some minor kernel driver tweaks will likely need to be made to get the G923 to work as well. I will gladly move all of this somewhere else as I do realized modifying the kernel is far beyond the scope of this project, I just think it would be a good idea to have this somewhere easily accessible, such as this project, for anyone that might be in the same situation as me and @kdw2060.

I don't think this project is the best place to discuss adding support for the G923 into the kernel, but I'm not against talking about it as a previous step.

Have you got the G923 working with the HID++ driver? I'm not sure how far have you've gone.

You should first confirm it's a standard HID++ device, then some changes should be made to the hid-logitech-hidpp module: adding the id and possibly some other adjustment.

Since the original issue was a question that's already answered, and there's already an open PR for adding support to Oversteer, I'd leave this issue closed for now.

**Comment by ZRtmWrJqXcjbqBLIMBYMCeUw** [comment]
I do not have the G923 working with the HID++ driver yet. I do also need to confirm that it is a standard HID++ device. I have added the id but there is probably more to it.

And I see no problem with keeping this issue closed for the reasons you mentioned.
