### ISSUE TITLE
[Feature request] Combine any axis

### ISSUE THREAD

**Issue by joslw** [berarma/oversteer#4]
Hi,
Not an issue but I don't know where to post this.
Would it be possible to introduce a function to combine any axis?
For instance it would be nice to be able to use clutch and gas to simulate rudder pedals as the brake is to stiff for this.
Thanks for your great program !

**Comment by berarma** [comment]
No as far as I know. This utility configures the hardware's driver and it can only do what you see. Maybe there's some way to remap axis using udev or SDL.

I'll leave this request open since I would like to investigate it further. If possible I'd try to implement it but there's no eta.

**Comment by joslw** [comment]
Thanks for your interest.

**Comment by berarma** [comment]
I've looked up some possible solutions outside of Oversteer since I don't if and when it would be possible to implement. Maybe you've done so already but I'll put it here anyway if it helps anyone.

- Combining them in the game in case it supports this kind of configuration or through a plugin/mod.
- Someone has swapped the wiring of the clutch and brake so they can be combined by the hardware driver, but then when playing racing games you'd have to change the default pedal configuration in the game.
- I guess the rubber piece that makes the brake harder could be removed but then it wouldn't feel like a brake in racing games.

**Comment by berarma** [comment]
I've written a new driver for Logitech wheels (except the G920) to improve FF support and I've also included this option. If you own a G25, G27 or G29 you can try it. You have to build it and load it manually, and Oversteer still doesn't support this option, so you'd have to set it from the command line.

**Comment by berarma** [comment]
Oversteer has been updated to support the new features in [new-lg4ff](https://github.com/berarma/new-lg4ff) and there's an option for combining gas and clutch. It's in the master branch, pending a release.
