### ISSUE TITLE
Disable oversteer option

### ISSUE THREAD

**Issue by GeoffreyDijkstra** [berarma/oversteer#66]
Hello,

Is it possible to disable oversteer (or only run it for specific games)?

The reason I asked is, I used oversteer to lock steering wheel (g29) tot 270 degrees for Need For Speed Underground 2 and heavily modified FFB settings. But if I close oversteer application and start Euro Truck Simulator 2 for example in which the g29 worked perfectly before I installed oversteer everything is now locked to configured settings for NFS UG2. I only wanted to configure that game not fuckup ever other game.

Otherwise this is an awesome addition for the wheel :)

**Comment by isopix** [comment]
It's not about not starting starting Oversteer, becus it modifies
driver settings semi-permamently(until reboot).

Runtime detection can be added to Oversteer, but if, it' completely
another question.
It need to monior then what processes are running, and modify settings
accordingly.

You can write easily you own script in bash that will do
while true; do ps aux | grep YourGame.exe && echo somevalue > /proc
(or /sys, whenever whee settings are pressented); sleep 1; done
mybe you can make profiles in Oversteer and load them (insted of
writing to /dev, /proc or /sys direcly...)
so it's not hard to make i in hacky way. As yoou see it's one-liner
that you can write in 5minutes and later debug it in another 15minutes
;)

cheers,
Krzysztof Krakowiak

**Comment by berarma** [comment]
As a clarification, Oversteer is only enabled while the application is running.

When it exists, the last settings you used are kept. I guess you would like that it restored the previous settings.

I, and probably others, use it in a different way though. We run Oversteer everytime we want to change some settings and keep it closed in between. Or maybe we run it for every game that uses the wheel with our custom presets or maybe even using a default preset for some games.

Your use case is different though since you want to use your custom settings just for one game and then use the default settings for everything else without intervention.

I can add an option so that the original settings are restored when exiting the app. I just wouldn't do it by default since I think most users expect the changes to be permanent for the session, thus not needing to keep the app open.

**Comment by writequit** [comment]
I dealt with this by making a "default" profile with the initial settings that I can switch back to.

Regards,
Geoff

**Comment by alexbrrsclnt** [comment]
Why not use profiles for each game, or at least, a default profile with common settings for all games, and one profile with changes  for NFS Underground 2?

Profiles are already there for that purpose

**Comment by GeoffreyDijkstra** [comment]
@berarma that makes sense, I think by creating a default profile as @writequit suggested might be the solution for me however there is no option that I can see to restore "defaults" so I actually don't know the g29 defaults (and already changed it for ug2 :man_facepalming:) so cannot create this profile, any idea on how to restore them to defaults? (maybe add button for this?)

Also you mentioned that closing the program would keep the settings, but if i close the program NFS UG2 actually forgets the settings (might just be an issue with this specific game and oversteer).

**Comment by berarma** [comment]
> @berarma that makes sense, I think by creating a default profile as @writequit suggested might be the solution for me however there is no option that I can see to restore "defaults" so I actually don't know the g29 defaults (and already changed it for ug2 :man_facepalming:) so cannot create this profile, any idea on how to restore them to defaults? (maybe add button for this?)

The original settings are restored after a reboot or when reconnecting the wheel. Then start Oversteer and save the current settings to a profile.

> Also you mentioned that closing the program would keep the settings, but if i close the program NFS UG2 actually forgets the settings (might just be an issue with this specific game and oversteer).

Well, it does nothing to preserve them though. If something else changes them you'll need to set them again. These settings are available to any app, not only Oversteer. Normally games don't change those settings, but I don't know the specifics of that game.

**Comment by isopix** [comment]
On 6/22/21, Bernat ***@***.***> wrote:
> Normally games don't change those settings, but I don't
> know the specifics of that game.

I strongly disagree with this statement, because while games can
internally scale force feedback gain, etc, the only practical way to
change some settings, like i.e. wheel rotation/turn zone in degrees,
the only practical way is set it trough drivers.

If I am wrong, then please correct me.

cheers,
Krzysztof Krakowiak

**Comment by berarma** [comment]
> On 6/22/21, Bernat ***@***.***> wrote:
> > Normally games don't change those settings, but I don't
> > know the specifics of that game.
> 
> I strongly disagree with this statement, because while games can
> internally scale force feedback gain, etc, the only practical way to
> change some settings, like i.e. wheel rotation/turn zone in degrees,
> the only practical way is set it trough drivers.
> 
> If I am wrong, then please correct me.
> 
> cheers,
> Krzysztof Krakowiak
> 

While games can change anything, like I said, they tend to do everything internally, specially since some features aren't easily available, only in sysfs.

Wheel rotation can be changed by locking the wheel range using FFB forces, the same way the firmware does.

Proton doesn't allow access to those features, except gain, and I don't know any native games that change them.

Anyway, better yalk about specific cases and problems to focus on something to solve.
