### ISSUE TITLE
No autocenter on rFactor 2

### ISSUE THREAD

**Issue by wleoncio** [berarma/oversteer#69]
Whenever I plug in my G29 and load a profile on Oversteer, I need to manually change the autocenter strength to get it to "bite", so the wheel feels firm and tries to stay centered. Then I am usually able to load the game and everything is fine.

However, things don't work as well when playing rFactor 2. I load the game and everything seems fine up until I get on the cockpit. Then the wheel feels flimsy again and going back to Oversteer just repeats the whole process. Other FFB effects seem fine, although a bit too mild.

Running Endeavour OS (Arch-based) with the `new-lg4ff-dkms-git` package installed. Also tried running Oversteer with sudo, but it doesn't make a difference.

**Comment by berarma** [comment]
I'm not sure about your intentions. Do you want the wheel to stay autocentered all the time, even when playing, or only until you get into the car?

I play rFactor 2 with a G29 and I don't need to set autocenter. In fact, I think autocenter is only useful for games that don't have any FFB. It could be nice for keeping the wheel centered while you're not yet driving but that's not possible, it should be handled by the game.

**Comment by wleoncio** [comment]
I just like the wheel stiffness and resistance that autocenter provides. Without it, it just feels like driving a car with lots of power steering, which dampens the feeling of all the forces acting on the car. Is that just me? 😅

**Comment by berarma** [comment]
I'm surprised. I guess it depends on what you're used to.

Autocentering is a fake force. It might make your wheel stiffer but in an unrealistic way. Wheels don't autocenter when the car is still, for example.

rFactor 2 has an option called something like "minimum torque" in ffb settings. It should be set to 9 for our wheel to make it more responsive. Higher values might make the wheel shake.

You can use the ffb multiplier to multiply the forces, but then you'd have lots of ffb clipping. If your only use for ffb is feeling like you're dragging the wheels, this might be what you're after. If you intend to notice the behavior of the tires to make corrections on the limit of grip, you don't want too much clipping. I'll leave it to the default value of 1 since that produces little clipping and more detailed and useful feedback.

Our wheels don't produce lots of force, they are relatively weak. Using a good part of that power to make the wheel stiffer would reduce the range of forces that can be produced. That is, the forces would be pretty similar no matter what the car was doing and we would feel little more than the force changing direction.

I don't think the ffb can be improved in rFactor 2, I just use the default settings and I think it's the best we can get on that wheel.

**Comment by wleoncio** [comment]
Thanks for the tips, I'm looking forward to trying them!

To better explain the autocentering effect I'm looking for: you know how wheels tend to go back to a straight position after you accelerate out of a turn (so you can often just let go of the wheel when getting out of sharp turns)? That's what I'm talking about, always assumed that's what autocenter does, but I'm starting to think I'm wrong.

**Comment by berarma** [comment]
No, the autocentering in Oversteer is a continuous centering force. It's normally used to return the wheel to its center position or keep it there until you start driving. It's also useful when the game doesn't support ffb, it's better than a loose wheel.

The ffb settings in Oversteer won't help you in rF2. Only the global ffb gain will affect. This game doesn't use pre-baked effects, it calculates the force on the fly from the physics so there's little you can tweak.

The centering effect you're talking about should be present without changing any settings. But if you accelerate too much at the exit the rear tires might slip and the wheel might move off center too.

**Comment by wleoncio** [comment]
Thank you for the explanation, I'm looking forward to trying all this when I'm back home. For now, I think the following is enough to close this issue:

> The ffb settings in Oversteer won't help you in rF2. Only the global ffb gain will affect. This game doesn't use pre-baked effects, it calculates the force on the fly from the physics so there's little you can tweak.
